//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirSOAP.SERECI {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estadoCivilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datosPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datosMadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fechaDefuncionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string causaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsumirSOAP.SERECI.Esposo esposoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaNacimientoField, value) != true)) {
                    this.fechaNacimientoField = value;
                    this.RaisePropertyChanged("fechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                if ((object.ReferenceEquals(this.sexoField, value) != true)) {
                    this.sexoField = value;
                    this.RaisePropertyChanged("sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string estadoCivil {
            get {
                return this.estadoCivilField;
            }
            set {
                if ((object.ReferenceEquals(this.estadoCivilField, value) != true)) {
                    this.estadoCivilField = value;
                    this.RaisePropertyChanged("estadoCivil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string carnet {
            get {
                return this.carnetField;
            }
            set {
                if ((object.ReferenceEquals(this.carnetField, value) != true)) {
                    this.carnetField = value;
                    this.RaisePropertyChanged("carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string datosPadre {
            get {
                return this.datosPadreField;
            }
            set {
                if ((object.ReferenceEquals(this.datosPadreField, value) != true)) {
                    this.datosPadreField = value;
                    this.RaisePropertyChanged("datosPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string datosMadre {
            get {
                return this.datosMadreField;
            }
            set {
                if ((object.ReferenceEquals(this.datosMadreField, value) != true)) {
                    this.datosMadreField = value;
                    this.RaisePropertyChanged("datosMadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string fechaDefuncion {
            get {
                return this.fechaDefuncionField;
            }
            set {
                if ((object.ReferenceEquals(this.fechaDefuncionField, value) != true)) {
                    this.fechaDefuncionField = value;
                    this.RaisePropertyChanged("fechaDefuncion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string causa {
            get {
                return this.causaField;
            }
            set {
                if ((object.ReferenceEquals(this.causaField, value) != true)) {
                    this.causaField = value;
                    this.RaisePropertyChanged("causa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public ConsumirSOAP.SERECI.Esposo esposo {
            get {
                return this.esposoField;
            }
            set {
                if ((object.ReferenceEquals(this.esposoField, value) != true)) {
                    this.esposoField = value;
                    this.RaisePropertyChanged("esposo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Esposo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Esposo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string carnetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string primerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string segundoApellidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string carnet {
            get {
                return this.carnetField;
            }
            set {
                if ((object.ReferenceEquals(this.carnetField, value) != true)) {
                    this.carnetField = value;
                    this.RaisePropertyChanged("carnet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.primerApellidoField, value) != true)) {
                    this.primerApellidoField = value;
                    this.RaisePropertyChanged("primerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.segundoApellidoField, value) != true)) {
                    this.segundoApellidoField = value;
                    this.RaisePropertyChanged("segundoApellido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SERECI.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        ConsumirSOAP.SERECI.ObtenerDatosResponse ObtenerDatos(ConsumirSOAP.SERECI.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerDatosResponse> ObtenerDatosAsync(ConsumirSOAP.SERECI.ObtenerDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoResponse ObtenerCertificadoNacimiento(ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoNacimiento", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioResponse ObtenerCertificadoMatrimonio(ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCertificadoMatrimonio", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCeritificadoDefunsion", ReplyAction="*")]
        ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionResponse ObtenerCeritificadoDefunsion(ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCeritificadoDefunsion", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionResponse> ObtenerCeritificadoDefunsionAsync(ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirSOAP.SERECI.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest() {
        }
        
        public ObtenerDatosRequest(ConsumirSOAP.SERECI.ObtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerDatosRequestBody() {
        }
        
        public ObtenerDatosRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirSOAP.SERECI.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse() {
        }
        
        public ObtenerDatosResponse(ConsumirSOAP.SERECI.ObtenerDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirSOAP.SERECI.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody() {
        }
        
        public ObtenerDatosResponseBody(ConsumirSOAP.SERECI.Persona ObtenerDatosResult) {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimiento", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequestBody Body;
        
        public ObtenerCertificadoNacimientoRequest() {
        }
        
        public ObtenerCertificadoNacimientoRequest(ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerCertificadoNacimientoRequestBody() {
        }
        
        public ObtenerCertificadoNacimientoRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoNacimientoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoNacimientoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoResponseBody Body;
        
        public ObtenerCertificadoNacimientoResponse() {
        }
        
        public ObtenerCertificadoNacimientoResponse(ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoNacimientoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirSOAP.SERECI.Persona ObtenerCertificadoNacimientoResult;
        
        public ObtenerCertificadoNacimientoResponseBody() {
        }
        
        public ObtenerCertificadoNacimientoResponseBody(ConsumirSOAP.SERECI.Persona ObtenerCertificadoNacimientoResult) {
            this.ObtenerCertificadoNacimientoResult = ObtenerCertificadoNacimientoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonio", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequestBody Body;
        
        public ObtenerCertificadoMatrimonioRequest() {
        }
        
        public ObtenerCertificadoMatrimonioRequest(ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerCertificadoMatrimonioRequestBody() {
        }
        
        public ObtenerCertificadoMatrimonioRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCertificadoMatrimonioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCertificadoMatrimonioResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioResponseBody Body;
        
        public ObtenerCertificadoMatrimonioResponse() {
        }
        
        public ObtenerCertificadoMatrimonioResponse(ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCertificadoMatrimonioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirSOAP.SERECI.Persona ObtenerCertificadoMatrimonioResult;
        
        public ObtenerCertificadoMatrimonioResponseBody() {
        }
        
        public ObtenerCertificadoMatrimonioResponseBody(ConsumirSOAP.SERECI.Persona ObtenerCertificadoMatrimonioResult) {
            this.ObtenerCertificadoMatrimonioResult = ObtenerCertificadoMatrimonioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCeritificadoDefunsionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCeritificadoDefunsion", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequestBody Body;
        
        public ObtenerCeritificadoDefunsionRequest() {
        }
        
        public ObtenerCeritificadoDefunsionRequest(ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCeritificadoDefunsionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public ObtenerCeritificadoDefunsionRequestBody() {
        }
        
        public ObtenerCeritificadoDefunsionRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerCeritificadoDefunsionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerCeritificadoDefunsionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionResponseBody Body;
        
        public ObtenerCeritificadoDefunsionResponse() {
        }
        
        public ObtenerCeritificadoDefunsionResponse(ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerCeritificadoDefunsionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirSOAP.SERECI.Persona ObtenerCeritificadoDefunsionResult;
        
        public ObtenerCeritificadoDefunsionResponseBody() {
        }
        
        public ObtenerCeritificadoDefunsionResponseBody(ConsumirSOAP.SERECI.Persona ObtenerCeritificadoDefunsionResult) {
            this.ObtenerCeritificadoDefunsionResult = ObtenerCeritificadoDefunsionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumirSOAP.SERECI.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumirSOAP.SERECI.WebService1Soap>, ConsumirSOAP.SERECI.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirSOAP.SERECI.ObtenerDatosResponse ConsumirSOAP.SERECI.WebService1Soap.ObtenerDatos(ConsumirSOAP.SERECI.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public ConsumirSOAP.SERECI.Persona ObtenerDatos(string ci) {
            ConsumirSOAP.SERECI.ObtenerDatosRequest inValue = new ConsumirSOAP.SERECI.ObtenerDatosRequest();
            inValue.Body = new ConsumirSOAP.SERECI.ObtenerDatosRequestBody();
            inValue.Body.ci = ci;
            ConsumirSOAP.SERECI.ObtenerDatosResponse retVal = ((ConsumirSOAP.SERECI.WebService1Soap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerDatosResponse> ConsumirSOAP.SERECI.WebService1Soap.ObtenerDatosAsync(ConsumirSOAP.SERECI.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerDatosResponse> ObtenerDatosAsync(string ci) {
            ConsumirSOAP.SERECI.ObtenerDatosRequest inValue = new ConsumirSOAP.SERECI.ObtenerDatosRequest();
            inValue.Body = new ConsumirSOAP.SERECI.ObtenerDatosRequestBody();
            inValue.Body.ci = ci;
            return ((ConsumirSOAP.SERECI.WebService1Soap)(this)).ObtenerDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoResponse ConsumirSOAP.SERECI.WebService1Soap.ObtenerCertificadoNacimiento(ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimiento(request);
        }
        
        public ConsumirSOAP.SERECI.Persona ObtenerCertificadoNacimiento(string ci) {
            ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequest inValue = new ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.ci = ci;
            ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoResponse retVal = ((ConsumirSOAP.SERECI.WebService1Soap)(this)).ObtenerCertificadoNacimiento(inValue);
            return retVal.Body.ObtenerCertificadoNacimientoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoResponse> ConsumirSOAP.SERECI.WebService1Soap.ObtenerCertificadoNacimientoAsync(ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequest request) {
            return base.Channel.ObtenerCertificadoNacimientoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoResponse> ObtenerCertificadoNacimientoAsync(string ci) {
            ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequest inValue = new ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequest();
            inValue.Body = new ConsumirSOAP.SERECI.ObtenerCertificadoNacimientoRequestBody();
            inValue.Body.ci = ci;
            return ((ConsumirSOAP.SERECI.WebService1Soap)(this)).ObtenerCertificadoNacimientoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioResponse ConsumirSOAP.SERECI.WebService1Soap.ObtenerCertificadoMatrimonio(ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequest request) {
            return base.Channel.ObtenerCertificadoMatrimonio(request);
        }
        
        public ConsumirSOAP.SERECI.Persona ObtenerCertificadoMatrimonio(string ci) {
            ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequest inValue = new ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.ci = ci;
            ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioResponse retVal = ((ConsumirSOAP.SERECI.WebService1Soap)(this)).ObtenerCertificadoMatrimonio(inValue);
            return retVal.Body.ObtenerCertificadoMatrimonioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioResponse> ConsumirSOAP.SERECI.WebService1Soap.ObtenerCertificadoMatrimonioAsync(ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequest request) {
            return base.Channel.ObtenerCertificadoMatrimonioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioResponse> ObtenerCertificadoMatrimonioAsync(string ci) {
            ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequest inValue = new ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequest();
            inValue.Body = new ConsumirSOAP.SERECI.ObtenerCertificadoMatrimonioRequestBody();
            inValue.Body.ci = ci;
            return ((ConsumirSOAP.SERECI.WebService1Soap)(this)).ObtenerCertificadoMatrimonioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionResponse ConsumirSOAP.SERECI.WebService1Soap.ObtenerCeritificadoDefunsion(ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequest request) {
            return base.Channel.ObtenerCeritificadoDefunsion(request);
        }
        
        public ConsumirSOAP.SERECI.Persona ObtenerCeritificadoDefunsion(string ci) {
            ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequest inValue = new ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequest();
            inValue.Body = new ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequestBody();
            inValue.Body.ci = ci;
            ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionResponse retVal = ((ConsumirSOAP.SERECI.WebService1Soap)(this)).ObtenerCeritificadoDefunsion(inValue);
            return retVal.Body.ObtenerCeritificadoDefunsionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionResponse> ConsumirSOAP.SERECI.WebService1Soap.ObtenerCeritificadoDefunsionAsync(ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequest request) {
            return base.Channel.ObtenerCeritificadoDefunsionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionResponse> ObtenerCeritificadoDefunsionAsync(string ci) {
            ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequest inValue = new ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequest();
            inValue.Body = new ConsumirSOAP.SERECI.ObtenerCeritificadoDefunsionRequestBody();
            inValue.Body.ci = ci;
            return ((ConsumirSOAP.SERECI.WebService1Soap)(this)).ObtenerCeritificadoDefunsionAsync(inValue);
        }
    }
}
