//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirBNB.BNB {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nrocuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string saldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nrocuenta {
            get {
                return this.nrocuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.nrocuentaField, value) != true)) {
                    this.nrocuentaField = value;
                    this.RaisePropertyChanged("nrocuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string saldo {
            get {
                return this.saldoField;
            }
            set {
                if ((object.ReferenceEquals(this.saldoField, value) != true)) {
                    this.saldoField = value;
                    this.RaisePropertyChanged("saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BNB.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsumirBNB.BNB.HelloWorldResponse HelloWorld(ConsumirBNB.BNB.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirBNB.BNB.HelloWorldResponse> HelloWorldAsync(ConsumirBNB.BNB.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nrocuenta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaSaldo", ReplyAction="*")]
        ConsumirBNB.BNB.ConsultaSaldoResponse ConsultaSaldo(ConsumirBNB.BNB.ConsultaSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaSaldo", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumirBNB.BNB.ConsultaSaldoResponse> ConsultaSaldoAsync(ConsumirBNB.BNB.ConsultaSaldoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirBNB.BNB.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsumirBNB.BNB.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirBNB.BNB.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsumirBNB.BNB.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldo", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirBNB.BNB.ConsultaSaldoRequestBody Body;
        
        public ConsultaSaldoRequest() {
        }
        
        public ConsultaSaldoRequest(ConsumirBNB.BNB.ConsultaSaldoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaSaldoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nrocuenta;
        
        public ConsultaSaldoRequestBody() {
        }
        
        public ConsultaSaldoRequestBody(string nrocuenta) {
            this.nrocuenta = nrocuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaSaldoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumirBNB.BNB.ConsultaSaldoResponseBody Body;
        
        public ConsultaSaldoResponse() {
        }
        
        public ConsultaSaldoResponse(ConsumirBNB.BNB.ConsultaSaldoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaSaldoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumirBNB.BNB.Cliente ConsultaSaldoResult;
        
        public ConsultaSaldoResponseBody() {
        }
        
        public ConsultaSaldoResponseBody(ConsumirBNB.BNB.Cliente ConsultaSaldoResult) {
            this.ConsultaSaldoResult = ConsultaSaldoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ConsumirBNB.BNB.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ConsumirBNB.BNB.WebService1Soap>, ConsumirBNB.BNB.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirBNB.BNB.HelloWorldResponse ConsumirBNB.BNB.WebService1Soap.HelloWorld(ConsumirBNB.BNB.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsumirBNB.BNB.HelloWorldRequest inValue = new ConsumirBNB.BNB.HelloWorldRequest();
            inValue.Body = new ConsumirBNB.BNB.HelloWorldRequestBody();
            ConsumirBNB.BNB.HelloWorldResponse retVal = ((ConsumirBNB.BNB.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirBNB.BNB.HelloWorldResponse> ConsumirBNB.BNB.WebService1Soap.HelloWorldAsync(ConsumirBNB.BNB.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirBNB.BNB.HelloWorldResponse> HelloWorldAsync() {
            ConsumirBNB.BNB.HelloWorldRequest inValue = new ConsumirBNB.BNB.HelloWorldRequest();
            inValue.Body = new ConsumirBNB.BNB.HelloWorldRequestBody();
            return ((ConsumirBNB.BNB.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumirBNB.BNB.ConsultaSaldoResponse ConsumirBNB.BNB.WebService1Soap.ConsultaSaldo(ConsumirBNB.BNB.ConsultaSaldoRequest request) {
            return base.Channel.ConsultaSaldo(request);
        }
        
        public ConsumirBNB.BNB.Cliente ConsultaSaldo(string nrocuenta) {
            ConsumirBNB.BNB.ConsultaSaldoRequest inValue = new ConsumirBNB.BNB.ConsultaSaldoRequest();
            inValue.Body = new ConsumirBNB.BNB.ConsultaSaldoRequestBody();
            inValue.Body.nrocuenta = nrocuenta;
            ConsumirBNB.BNB.ConsultaSaldoResponse retVal = ((ConsumirBNB.BNB.WebService1Soap)(this)).ConsultaSaldo(inValue);
            return retVal.Body.ConsultaSaldoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumirBNB.BNB.ConsultaSaldoResponse> ConsumirBNB.BNB.WebService1Soap.ConsultaSaldoAsync(ConsumirBNB.BNB.ConsultaSaldoRequest request) {
            return base.Channel.ConsultaSaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumirBNB.BNB.ConsultaSaldoResponse> ConsultaSaldoAsync(string nrocuenta) {
            ConsumirBNB.BNB.ConsultaSaldoRequest inValue = new ConsumirBNB.BNB.ConsultaSaldoRequest();
            inValue.Body = new ConsumirBNB.BNB.ConsultaSaldoRequestBody();
            inValue.Body.nrocuenta = nrocuenta;
            return ((ConsumirBNB.BNB.WebService1Soap)(this)).ConsultaSaldoAsync(inValue);
        }
    }
}
